FROM node:8.16.0-alpine AS frontend-build

ADD ./frontend /app
WORKDIR /app

RUN npm config set unsafe-perm true
RUN npm install -g yarn && yarn install --registry=https://registry.npm.taobao.org

RUN npm run build:prod


FROM node:8.16.0-alpine

RUN npm install -g serve

WORKDIR /app

COPY --from=frontend-build /app/dist /app/dist

COPY docker_init.sh docker_init.sh

EXPOSE 5000

CMD ["/bin/sh", "/app/docker_init.sh"]
